### ISSUE TITLE
forums plugin does not use commands

### ISSUE THREAD

**Issue by an-OK-squirrel** [an-OK-squirrel/ATer-bot#2]
thus !new does not work but simply "new" does. will fix in a sec

edit: Just got a BSOD. Going to figure out what happened.

**Comment by robinp7720** [comment]
I'm using the onMessage event for it on purpose

**Comment by an-OK-squirrel** [comment]
why?

**Comment by robinp7720** [comment]
Its somthing that probably everyone doesn't mind seeing

**Comment by an-OK-squirrel** [comment]
but !new would be better

**Comment by an-OK-squirrel** [comment]
Also, I was thinking more of a thing that would tell you when a new post happens, rather than the newest post

**Comment by an-OK-squirrel** [comment]
Also, check out this: https://scratch.mit.edu/discuss/m/31/
Easier to understand classess

**Comment by an-OK-squirrel** [comment]
We should use that

Also should we think about a swear filter?

**Comment by robinp7720** [comment]
Make a plugin!
use the onMessage event and return something like "Oi! watch ya language!"

**Comment by an-OK-squirrel** [comment]
lol k

**Comment by an-OK-squirrel** [comment]
should I obfuscate it by like rot13 or something easy like that

**Comment by an-OK-squirrel** [comment]
Also, it should warn the user, then kick

**Comment by robinp7720** [comment]
It would need op for that, not possible with the current plugins system (I could easily change this) and no, No need to obfuscate it. This is github. Not Scratch

**Comment by an-OK-squirrel** [comment]
We're linking it though.

**Comment by an-OK-squirrel** [comment]
Hey, lookie here! I've been running the bot for a minute and no blue screen of death! :D

**Comment by robinp7720** [comment]
You you really want to obfuscate it, be my guest :p

**Comment by an-OK-squirrel** [comment]
seriously tho, this should be a command, not a word

**Comment by an-OK-squirrel** [comment]
> <Ater-Bot1> Welcome to ##ater-bot Ater-Bot1! 
Will do a fix for this

**Comment by robinp7720** [comment]
It can always be a command... just use the onCommand instead of onMessage.
and BSOD occur because you ran out of ram, which windows doesnt handle very well atall.

easy fix if nick != bot.nick

**Comment by an-OK-squirrel** [comment]
yeah, was going to thanks.

**Comment by an-OK-squirrel** [comment]
dump of BSOD btw: http://i.imgur.com/cpC5y7i.png

**Comment by robinp7720** [comment]
Doesn't say a single usefull thing :p

**Comment by an-OK-squirrel** [comment]
really?

**Comment by robinp7720** [comment]
Yea..
Checkout the dumps

**Comment by an-OK-squirrel** [comment]
Seems just by viewing a Scratch page I get up to 90% CPU usage.

**Comment by an-OK-squirrel** [comment]
BTW I didn't get a _dump_ onscreen
I got random pixels

**Comment by robinp7720** [comment]
displayed as fullpath on your window thing

**Comment by robinp7720** [comment]
CPU is not RAM

**Comment by an-OK-squirrel** [comment]
Oh yeah, whoops

**Comment by robinp7720** [comment]
windows handles memory insanly badly

**Comment by an-OK-squirrel** [comment]
really?

**Comment by an-OK-squirrel** [comment]
Well I'm using 1GB right now out of 2GB, I'll be fine :P

**Comment by robinp7720** [comment]
yea.. Very Baddly

**Comment by robinp7720** [comment]
using half a gig with a  bot, multiple windows of firefox, thunderbird, webstorm, terminal and hexchat

**Comment by an-OK-squirrel** [comment]
Good thing I'm getting a new PC soon. It will have 8GB so it shouldn't be a problem

**Comment by robinp7720** [comment]
I upgraded I my laptop from 4gb to 8gb. The motherboard supports up to 16gb though

**Comment by an-OK-squirrel** [comment]
Mine supports 2GB

**Comment by robinp7720** [comment]
You're probably able to upgrade it to 4 or 8 gb

**Comment by an-OK-squirrel** [comment]
Nope. It's very very old

**Comment by an-OK-squirrel** [comment]
Dell inspiron 9400

**Comment by robinp7720** [comment]
It has a dedicated graphics card!

**Comment by an-OK-squirrel** [comment]
what do you mean?

**Comment by robinp7720** [comment]
Maye not..

**Comment by an-OK-squirrel** [comment]
Anyways, pushed.

**Comment by robinp7720** [comment]
I pushed it before you did..

**Comment by an-OK-squirrel** [comment]
dangit

**Comment by robinp7720** [comment]
Lol, you overwrote my changes :p

**Comment by an-OK-squirrel** [comment]
Sorry!

**Comment by an-OK-squirrel** [comment]
Going to push fix in a minute
